model:
  type: Bert
dataset: imdb
dataroot: /home/renshuhuai/TextAutoAugment/data/aclImdb
aug: imdb
per_device_train_batch_size: 64
per_device_eval_batch_size: 128
epoch: 10
lr: 4e-5
max_seq_length: 128
