model:
  type: Bert
dataset: trec
dataroot: /home/renshuhuai/TextAutoAugment/data/trec
aug: trec
per_device_train_batch_size: 64
per_device_eval_batch_size: 128
epoch: 20
lr: 4e-5
max_seq_length: 128
